---
- name: Copy the redisb.yaml file
  blockinfile:
   dest: /etc/dd-agent/conf.d/redisdb.yaml
   create: yes
   group: root
   owner: dd-agent
   mode: 0644
   block: |
      init_config:
      instances:
         - host: localhost
           port: 6379
- name: Restart the dd_agent
  service: name=datadog-agent state=restarted

