---
- name: Install datadog agent
  shell: DD_API_KEY={{ api_key }} bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/install_agent.sh)"
- name: Copy the process file
  template: src=process.yaml dest=/etc/dd-agent/conf.d/process.yaml owner=dd-agent group=root mode=0644
  notify: restart datadog-agent


    
